select * from customer;

--- Removing the corrupted value
UPDATE customer
SET review_rating = NULL
WHERE review_rating LIKE '<bound method%';

--- Verifying the values
SELECT review_rating
FROM customer
WHERE review_rating IS NOT NULL
  AND TRY_CAST(review_rating AS FLOAT) IS NULL;

--- Computing the median
WITH median_cte AS (
    SELECT PERCENTILE_CONT(0.5)
           WITHIN GROUP (ORDER BY TRY_CAST(review_rating AS FLOAT))
           OVER () AS median_rating
    FROM customer
    WHERE TRY_CAST(review_rating AS FLOAT) IS NOT NULL
)
UPDATE customer
SET review_rating = (
    SELECT TOP 1 median_rating
    FROM median_cte
)
WHERE review_rating IS NULL;

ALTER TABLE customer
ALTER COLUMN review_rating FLOAT;

--- Total revenue generated by Male vs Female customers
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender
order by sum(purchase_amount) desc;

--- Customers that used discounts but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and 
purchase_amount >( select avg(purchase_amount)
				from customer)
order by purchase_amount desc;

--- What are the Top 5 products with the highest avg review rating
select top 5 item_purchased, round(avg(review_rating),2) as Avg_Rating
from customer
group by item_purchased
order by avg(review_rating) desc;

--- Compare the average purchase amount based on shipping_type
select shipping_type, round(avg(purchase_amount),2) as Avg_Purchase_Amount
from customer
group by shipping_type
order by avg(purchase_amount) desc;


--- Compare the average purchase amount based on shipping_type
select shipping_type, round(avg(purchase_amount),2) as Avg_Purchase_Amount
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
order by avg(purchase_amount) desc;

--- Do subscribed customer spend more? Compare the average spend and total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as Avg_Purchase_Amount,
round(sum(purchase_amount),2) as Total_Revenue
from customer
group by subscription_status
order by round(avg(purchase_amount),2) , round(sum(purchase_amount),2) desc;

--- What are the top 5 that have the highest percentage of purchases with discount applied
select top 5 item_purchased,
round(count(case when discount_applied = 'Yes' then 1 end) * 100 / count(*),2) as discount_percent
from customer
group by item_purchased
order by discount_percent desc;

--- Segment customers into New, Returning, Loyal based on total number of previous purchases and show count of each segment
with customer_type as(
select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)

select customer_segment, count(*) as No_Of_Customer
from customer_type
group by customer_segment
order by No_Of_Customer desc;

---- Top 3 most purchased products within each category
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

--- Are customers who are repeat buyers (>5), also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
order by repeat_buyers desc;

--- What is the revenue contribution of each age group
select age_group, sum(purchase_amount) as Total_Revenue
from customer
group by age_group
order by Total_Revenue desc;
